# Generated by Django 6.0.3 on 2026-03-17 15:05

import uuid

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('department_type', models.CharField(choices=[('RECTORATE', 'Ректорат'), ('FACULTY', 'Факультет'), ('DEPARTMENT', 'Кафедра'), ('ADMIN_SERVICE', 'Административная служба'), ('SUPPORT_UNIT', 'Вспомогательное подразделение')], default='DEPARTMENT', max_length=20, verbose_name='Тип подразделения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department', verbose_name='Родительское подразделение')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Табельный номер')),
                ('hire_date', models.DateField(verbose_name='Дата принятия')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Основное место работы'), ('PART_TIME', 'Совместительство'), ('HOURLY', 'Почасовая оплата')], default='PERMANENT', max_length=15, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('ACTIVE', 'Работает'), ('ON_LEAVE', 'В отпуске'), ('DISMISSED', 'Уволен')], default='ACTIVE', max_length=15, verbose_name='Статус')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('pinfl', models.CharField(max_length=14, unique=True, validators=[apps.core.validators.validate_pinfl], verbose_name='ПИНФЛ')),
                ('inn', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[apps.core.validators.validate_inn], verbose_name='ИНН')),
                ('passport_series', models.CharField(max_length=9, verbose_name='Серия и номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=6, verbose_name='Пол')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_uzbekistan_phone], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department', verbose_name='Подразделение')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='departments.employee', verbose_name='Руководитель'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('category', models.CharField(choices=[('PPS', 'ППС (Профессорско-преподавательский состав)'), ('NS', 'НС (Научный сотрудник)'), ('AUP', 'АУП (Административно-управленческий персонал)'), ('UVP', 'УВП (Учебно-вспомогательный персонал)'), ('POP', 'ПОП (Прочий обслуживающий персонал)')], max_length=10, verbose_name='Категория')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная зарплата')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимальная зарплата')),
                ('is_academic', models.BooleanField(default=False, verbose_name='Академическая')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('change_reason', models.CharField(choices=[('HIRED', 'Принят на работу'), ('TRANSFERRED', 'Переведён'), ('PROMOTED', 'Повышен'), ('DISMISSED', 'Уволен')], max_length=20, verbose_name='Причина изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'История занятости',
                'verbose_name_plural': 'История занятости',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.position', verbose_name='Должность'),
        ),
    ]
