# Generated by Django 6.0.3 on 2026-03-17 15:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('days_per_year', models.PositiveIntegerField(verbose_name='Дней в год')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Оплачиваемый')),
                ('requires_document', models.BooleanField(default=False, verbose_name='Требует документ')),
                ('applicable_categories', models.JSONField(default=list, verbose_name='Применимые категории')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Тип отпуска',
                'verbose_name_plural': 'Типы отпусков',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('days_count', models.PositiveIntegerField(default=0, verbose_name='Количество дней')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING_HEAD', 'На рассмотрении у руководителя'), ('PENDING_HR', 'На рассмотрении HR'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено')], default='DRAFT', max_length=15, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype', verbose_name='Тип отпуска')),
            ],
            options={
                'verbose_name': 'Заявка на отпуск',
                'verbose_name_plural': 'Заявки на отпуск',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('is_working_day', models.BooleanField(default=False, verbose_name='Рабочий день (перенос)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Государственный праздник',
                'verbose_name_plural': 'Государственные праздники',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('total_days', models.PositiveIntegerField(verbose_name='Всего дней')),
                ('used_days', models.PositiveIntegerField(default=0, verbose_name='Использовано дней')),
                ('carry_over_days', models.PositiveIntegerField(default=0, verbose_name='Перенесённые дни')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='Тип отпуска')),
            ],
            options={
                'verbose_name': 'Начисление отпуска',
                'verbose_name_plural': 'Начисления отпусков',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
