# Generated by Django 6.0.3 on 2026-03-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveallocation',
            options={'ordering': ['-year'], 'verbose_name': 'Начисление отпуска', 'verbose_name_plural': 'Начисления отпусков'},
        ),
    ]
