# Generated by Django 6.0.3 on 2026-03-17 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('resume', models.FileField(blank=True, upload_to='resumes/%Y/%m/', verbose_name='Резюме')),
                ('source', models.CharField(choices=[('EXTERNAL', 'Внешний'), ('INTERNAL', 'Внутренний перевод'), ('REFERRAL', 'Рекомендация'), ('HEMIS', 'HEMIS')], default='EXTERNAL', max_length=10, verbose_name='Источник')),
                ('stage', models.CharField(choices=[('APPLIED', 'Подал заявку'), ('SCREENING', 'На проверке'), ('INTERVIEW', 'Интервью'), ('OFFER', 'Предложение'), ('HIRED', 'Принят'), ('REJECTED', 'Отклонён')], default='APPLIED', max_length=10, verbose_name='Стадия')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('applied_at', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Время интервью')),
                ('interview_type', models.CharField(choices=[('HR', 'HR интервью'), ('TECHNICAL', 'Техническое'), ('FINAL', 'Финальное')], max_length=15, verbose_name='Тип интервью')),
                ('result', models.CharField(choices=[('PENDING', 'Ожидание'), ('PASS', 'Прошёл'), ('FAIL', 'Не прошёл'), ('HOLD', 'На паузе')], default='PENDING', max_length=10, verbose_name='Результат')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Длительность (мин)')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.candidate', verbose_name='Кандидат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Интервьюер')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, verbose_name='Название')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('OPEN', 'Открыта'), ('CLOSED', 'Закрыта')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('vacancies_count', models.IntegerField(default=1, verbose_name='Количество мест')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='departments.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='departments.position', verbose_name='Должность')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.vacancy', verbose_name='Вакансия'),
        ),
    ]
