# Generated by Django 6.0.3 on 2026-03-18 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Uni-HRM', max_length=200, verbose_name='Site Name')),
                ('site_url', models.CharField(blank=True, max_length=200, verbose_name='Site URL')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Working Hours Start')),
                ('working_hours_end', models.TimeField(default='18:00', verbose_name='Working Hours End')),
                ('working_days', models.JSONField(default=list, verbose_name='Working Days')),
                ('annual_leave_days', models.PositiveIntegerField(default=28, verbose_name='Annual Leave Days')),
                ('sick_leave_days', models.PositiveIntegerField(default=14, verbose_name='Sick Leave Days')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Currency')),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50, verbose_name='Timezone')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP Use TLS')),
                ('smtp_username', models.CharField(blank=True, max_length=200, verbose_name='SMTP Username')),
                ('from_email', models.CharField(blank=True, max_length=200, verbose_name='From Email')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
