# Generated by Django 6.0.3 on 2026-03-17 21:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Академическая степень',
                'verbose_name_plural': 'Академические степени',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Академическое звание',
                'verbose_name_plural': 'Академические звания',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAcademic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Специализация')),
                ('dissertation_topic', models.TextField(blank=True, verbose_name='Тема диссертации')),
                ('diploma_number', models.CharField(blank=True, max_length=50, verbose_name='Номер диплома')),
                ('awarded_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='academic.academicdegree', verbose_name='Степень')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='departments.employee', verbose_name='Сотрудник')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='academic.academictitle', verbose_name='Звание')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Академические данные сотрудника',
                'verbose_name_plural': 'Академические данные сотрудников',
            },
        ),
        migrations.CreateModel(
            name='PositionContest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('application_deadline', models.DateField(verbose_name='Срок подачи заявок')),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=10, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='departments.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='departments.position', verbose_name='Должность')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to='departments.employee', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Конкурс на должность',
                'verbose_name_plural': 'Конкурсы на должности',
                'ordering': ['-application_deadline'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('credits', models.IntegerField(default=0, verbose_name='Кредиты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='departments.department', verbose_name='Кафедра')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9, verbose_name='Учебный год')),
                ('semester', models.IntegerField(choices=[(1, '1-й семестр'), (2, '2-й семестр')], verbose_name='Семестр')),
                ('lecture_hours', models.IntegerField(default=0, verbose_name='Лекции (часы)')),
                ('seminar_hours', models.IntegerField(default=0, verbose_name='Семинары (часы)')),
                ('lab_hours', models.IntegerField(default=0, verbose_name='Лабораторные (часы)')),
                ('load_type', models.CharField(choices=[('PRIMARY', 'Основная'), ('SECONDARY', 'Совместительство'), ('HOURLY', 'Почасовая')], default='PRIMARY', max_length=10, verbose_name='Тип нагрузки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='departments.employee', verbose_name='Преподаватель')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='academic.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Учебная нагрузка',
                'verbose_name_plural': 'Учебные нагрузки',
                'ordering': ['-academic_year', 'semester'],
                'unique_together': {('employee', 'subject', 'academic_year', 'semester')},
            },
        ),
    ]
