# Generated by Django 6.0.3 on 2026-03-17 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('active', 'Активный'), ('review', 'Рассмотрение'), ('completed', 'Завершён')], default='planning', max_length=20, verbose_name='Статус')),
                ('applicable_departments', models.ManyToManyField(blank=True, related_name='appraisal_cycles', to='departments.department', verbose_name='Применимые подразделения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Цикл аттестации',
                'verbose_name_plural': 'Циклы аттестации',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('self_review', 'Самооценка'), ('manager_review', 'Оценка руководителя'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Итоговый балл')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisal.appraisalcycle', verbose_name='Цикл')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='departments.employee', verbose_name='Сотрудник')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='departments.employee', verbose_name='Ревьюер')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Аттестация сотрудника',
                'verbose_name_plural': 'Аттестации сотрудников',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='KPIIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('academic', 'Академическая'), ('administrative', 'Административная'), ('research', 'Научная'), ('service', 'Служебная')], max_length=20, verbose_name='Категория')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес')),
                ('max_score', models.IntegerField(default=10, verbose_name='Максимальный балл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Показатель KPI',
                'verbose_name_plural': 'Показатели KPI',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_score', models.IntegerField(blank=True, null=True, verbose_name='Самооценка')),
                ('manager_score', models.IntegerField(blank=True, null=True, verbose_name='Оценка руководителя')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Итоговая оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='appraisal.employeeappraisal', verbose_name='Аттестация')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appraisal.kpiindicator', verbose_name='Показатель KPI')),
            ],
            options={
                'verbose_name': 'Оценка KPI',
                'verbose_name_plural': 'Оценки KPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Провайдер')),
                ('training_type', models.CharField(choices=[('internal', 'Внутренняя'), ('external', 'Внешняя'), ('online', 'Онлайн')], max_length=20, verbose_name='Тип обучения')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='Продолжительность (часы)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('enrolled', 'Зачислен'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='enrolled', max_length=20, verbose_name='Статус')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Номер сертификата')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Балл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='departments.employee', verbose_name='Сотрудник')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appraisal.trainingprogram', verbose_name='Программа')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Запись об обучении',
                'verbose_name_plural': 'Записи об обучении',
                'ordering': ['-created_at'],
            },
        ),
    ]
