# Generated by Django 6.0.3 on 2026-03-17 19:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год')),
                ('ndfl_rate', models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=5, verbose_name='Ставка НДФЛ')),
                ('social_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=5, verbose_name='Социальный налог')),
                ('inps_employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5, verbose_name='ИНПС (сотрудник)')),
                ('inps_employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5, verbose_name='ИНПС (работодатель)')),
                ('minimum_wage', models.DecimalField(decimal_places=2, default=Decimal('1155000'), max_digits=12, verbose_name='Минимальная зарплата')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Налоговая конфигурация',
                'verbose_name_plural': 'Налоговые конфигурации',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовый оклад')),
                ('academic_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Академическая надбавка %')),
                ('position_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Должностная надбавка %')),
                ('seniority_bonus_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Надбавка за стаж %')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Прочие надбавки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Зарплата сотрудника',
                'verbose_name_plural': 'Зарплаты сотрудников',
                'ordering': ['-effective_from'],
                'unique_together': {('employee', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Базовый оклад')),
                ('academic_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Академическая надбавка')),
                ('position_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Должностная надбавка')),
                ('seniority_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Надбавка за стаж')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Прочие надбавки')),
                ('working_days_in_month', models.PositiveIntegerField(default=0, verbose_name='Рабочих дней в месяце')),
                ('days_worked', models.PositiveIntegerField(default=0, verbose_name='Отработано дней')),
                ('days_on_leave', models.PositiveIntegerField(default=0, verbose_name='Дней в отпуске')),
                ('days_absent', models.PositiveIntegerField(default=0, verbose_name='Дней отсутствия')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Сверхурочные часы')),
                ('attendance_ratio', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=5, verbose_name='Коэффициент посещаемости')),
                ('overtime_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплата сверхурочных')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Начислено (gross)')),
                ('ndfl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='НДФЛ')),
                ('inps_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ИНПС (сотрудник)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Прочие удержания')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Итого удержания')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='К выплате (net)')),
                ('employer_social_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Соц. налог работодателя')),
                ('employer_inps', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ИНПС работодателя')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CALCULATED', 'Рассчитано'), ('APPROVED', 'Одобрено'), ('PAID', 'Выплачено')], default='DRAFT', max_length=15, verbose_name='Статус')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('tax_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.taxconfiguration', verbose_name='Налоговая конфигурация')),
            ],
            options={
                'verbose_name': 'Расчётный лист',
                'verbose_name_plural': 'Расчётные листы',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
