# Generated by Django 6.0.3 on 2026-03-17 15:50

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('schedule_type', models.CharField(choices=[('5/2', '5/2 (пн-пт)'), ('6/1', '6/1 (пн-сб)'), ('SHIFT', 'Сменный'), ('FLEXIBLE', 'Гибкий')], max_length=10, verbose_name='Тип')),
                ('work_start', models.TimeField(verbose_name='Начало работы')),
                ('work_end', models.TimeField(verbose_name='Конец работы')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('working_days', models.JSONField(default=list, verbose_name='Рабочие дни')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Рабочий график',
                'verbose_name_plural': 'Рабочие графики',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.workschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'График сотрудника',
                'verbose_name_plural': 'Графики сотрудников',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Приход')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Уход')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутствовал'), ('ABSENT', 'Отсутствовал'), ('LATE', 'Опоздал'), ('HALF_DAY', 'Неполный день'), ('ON_LEAVE', 'В отпуске'), ('HOLIDAY', 'Выходной/праздник')], max_length=10, verbose_name='Статус')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Рабочие часы')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Сверхурочные')),
                ('source', models.CharField(choices=[('MANUAL', 'Вручную'), ('IMPORT', 'Импорт'), ('BIOMETRIC', 'Биометрия')], default='MANUAL', max_length=10, verbose_name='Источник')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('total_working_days', models.PositiveIntegerField(default=0, verbose_name='Рабочих дней')),
                ('days_present', models.PositiveIntegerField(default=0, verbose_name='Присутствовал')),
                ('days_absent', models.PositiveIntegerField(default=0, verbose_name='Отсутствовал')),
                ('days_late', models.PositiveIntegerField(default=0, verbose_name='Опоздал')),
                ('days_on_leave', models.PositiveIntegerField(default=0, verbose_name='В отпуске')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Всего часов')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Сверхурочные')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Отправлен'), ('APPROVED', 'Утверждён')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='departments.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табели',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
